config/routes.rb
Rails.application.routes.draw do
  # Option 1
  post 'newsletter/subscribe', to: 'newsletter#subscribe', as: 'newsletter_subscribe'
  delete 'newsletter/unsubscribe', to: 'newsletter#unsubscribe', as: 'newsletter_unsubscribe' 

  # option 2
  post 'newsletter/manage', to: 'newsletter#manage', as: 'newsletter_manage'

  # Email newsletter users with the pat: email_blast_path
  post 'newsletter/email', to: 'newsletter#email', as: 'email_blast'

  # Other routes 
  root "pages#home"
  get "pages/home"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/newsletter.rb
class Newsletter < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_subscriptions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/newsletter_controller.rb
class NewsletterController < ApplicationController
  before_action :set_name, only: %i[subscribe unsubscribe manage email]
  before_action :authenticate_user!

  def subscribe
    current_user.subscribe(@name) unless current_user.subscribed?(@name)

    # use turbo to update the page

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to root_path }
    end
  end

  def unsubscribe
    current_user.unsubscribe(@name) if current_user.subscribed?(@name)

    # use turbo to update the page

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to root_path }
    end
  end

  def manage
    if current_user.subscribed?(@name)
      current_user.unsubscribe(@name)
    else
      current_user.subscribe(@name)
    end

    respond_to do |format|
      format.turbo_stream
      format.html {redirect_to root_path}
    end
  end

  def email
    @users = User.subscribed(@name)
    puts "Sending #{@name} newsletter to #{@users.count} users"
    @users.each do |user|
      puts "Sending email to #{user.email}"

      # use action_mailer to send the email
      NewsletterMailer.with(user:).email_blast(user, @name).deliver_later
    end

    redirect_to root_path

  end



  private

  def newsletter_params
    params.permit(:name, :_method, :authenticity_token)
  end

  def set_name
    @name = newsletter_params[:name]
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/newsletter_helper.rb
module NewsletterHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Hotturbo" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/mailkick/subscriptions/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Subscriptions</title>

    <style>
      body {
        padding: 20px;
        font-family: "Helvetica Neue", Arial, Helvetica, sans-serif;
        font-size: 14px;
        line-height: 1.4;
      }

      a {
        color: blue;
      }

      .container {
        max-width: 500px;
        margin-left: auto;
        margin-right: auto;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <% if !subscribed? %>
        <p>You are unsubscribed.</p>
        <p><%= link_to "Resubscribe", subscribe_url %></p>
      <% else %>
        <p>You are subscribed.</p>
        <p><%= link_to "Unsubscribe", unsubscribe_url %></p>
      <% end %>
    </div>
  </body>
</html>

app/views/newsletter/manage.turbo_stream.erb
<%= turbo_stream.replace "newsletter",
  partial: "shared/manage_newsletter",
  locals: {
    name: @name,
    user: current_user} %>

app/views/newsletter/subscribe.turbo_stream.erb
<%= turbo_stream.replace "newsletter",
  partial: "shared/newsletter",
  locals: {
    name: @name,
    user: current_user} %>

app/views/newsletter/unsubscribe.turbo_stream.erb
<%= turbo_stream.replace "newsletter",
  partial: "shared/newsletter",
  locals: {
    name: @name,
    user: current_user} %>

app/views/pages/home.html.erb
<div>
  <h1 class="font-bold text-4xl">Pages#home</h1>
  <p>Find me in app/views/pages/home.html.erb</p>
  <% if user_signed_in? %>
    <%= render "shared/manage_newsletter", name: "email_blast", user: current_user %>
    <%= link_to "Sign Out", destroy_user_session_path, data: {turbo_method: :delete} %>
  <% else %>
    <%= link_to "Sign In", new_user_session_path %>
  <% end %>
  <%= button_to "Email Users", email_blast_path(name: "email_blast"), metod: :post, data: {turbo_method: :post} %>
</div>

app/views/shared/_manage_newsletter.html.erb
<div id="newsletter">
  <% if user&.subscribed?(name) %>
    <%= button_to "Unsubscribe", newsletter_manage_path(name: name), method: :post, data: {turbo_method: :delete} %>
  <% else %>

    <div>
      <h2> Newsletter </h2>
      <p>Sign up for our newsletter to get the latest news and announcements. </p>
      <%= button_to "Subscribe", newsletter_manage_path(name: name), method: :post, data: {turbo_method: :post} %>
    </div>
  <% end %>
</div>

app/views/shared/_newsletter.html.erb
<div id="newsletter">
  <% if user&.subscribed?(name) %>
    <%= button_to "Unsubscribe", newsletter_unsubscribe_path(name: name), method: :delete, data: {turbo_method: :destroy} %>
  <% else %>

    <div>
      <h2> Newsletter </h2>
      <p>Sign up for our newsletter to get the latest news and announcements. </p>
      <%= button_to "Subscribe", newsletter_subscribe_path(name: name), method: :post, data: {turbo_method: :post} %>
    </div>
  <% end %>
</div>